### ISSUE TITLE
Support 2.6

### ISSUE THREAD

**Issue by anandology** [Anomareh/mynt#33]
mynt currently works only for Python 2.7.x as it uses some latest additions like:
-  `OrderedDict`
- `flags` keyword argument to `re.sub`
- calling function with `**d` when `d` has unicode keys

These must be fixed to be able to use mynt on older versions of Python. Python2.6 is the default version available on Debian stable, I think it'll be useful to support it.

**Comment by Mindiell** [comment]
Hi @Anomareh, I converted mynt to python 3.8 in order to help. I don't know if you're still on it (last commit from 2014).
I did not creat any pypi package for now as I would prefer to PR into the orginial mynt project, but I'm not sure you're still there.
I'm on IRC too, on the #mynt channel if needed.

My repo is simply https://github.com/Mindiell/mynt3

thx,

**Comment by Anomareh** [comment]
@Mindiell sorry, I was quickly going through issues and didn't see your post. I finally got some time to work on mynt and updated it to Python 3. Didn't mean to ignore your work. I just took a look at your repo and couldn't really tell what you had changed as everything was added in one commit, but if you made any other changes you'd like to see let me know and I can take a look!
